"""empty message

Revision ID: 05fc3c280b42
Revises: 300c2d222043
Create Date: 2024-10-24 14:50:47.417694

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05fc3c280b42'
down_revision = '300c2d222043'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('personal_rating', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author', sa.String(length=64), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('personal_rating', schema=None) as batch_op:
        batch_op.drop_column('author')

    # ### end Alembic commands ###
