"""empty message

Revision ID: e4f2e072888e
Revises: 47bc76a3f117
Create Date: 2024-10-24 15:08:59.772375

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4f2e072888e'
down_revision = '47bc76a3f117'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('personal_rating', schema=None) as batch_op:
        batch_op.add_column(sa.Column('game_name', sa.String(length=100), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('personal_rating', schema=None) as batch_op:
        batch_op.drop_column('game_name')

    # ### end Alembic commands ###
